### ISSUE TITLE
Mod incompatible with FabricLoader 0.15.3

### ISSUE THREAD

**Issue by ryanliii** [Aeldit/CyanSetHome#2]
I believe the latest version of your mod is incompatible with the latest possible version of FabricLoader for 1.20.1. If I'm mistaken I'm sorry, but it appears to be the issue based on the error log pasted below.

``
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'cyansh'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.15.3.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.3-launcher.1.0.0.jar:1.0.0]
Caused by: com.google.gson.JsonSyntaxException: java.nio.charset.MalformedInputException: Input length = 1
        at com.google.gson.Gson.fromJson(Gson.java:1229) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar:?]
        at fr.aeldit.cyansh.homes.Homes.readServer(Homes.java:299) ~[CyanSetHome-0.1.5+1.20.1.jar:?]
        at fr.aeldit.cyansh.CyanSHServerCore.onInitializeServer(CyanSHServerCore.java:40) ~[CyanSetHome-0.1.5+1.20.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
        ... 7 more
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:274) ~[?:?]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
        at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
        at java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
        at java.io.BufferedReader.read1(BufferedReader.java:213) ~[?:?]
        at java.io.BufferedReader.read(BufferedReader.java:287) ~[?:?]
        at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1349) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1387) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.java:1665) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:543) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1211) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar:?]
        at fr.aeldit.cyansh.homes.Homes.readServer(Homes.java:299) ~[CyanSetHome-0.1.5+1.20.1.jar:?]
        at fr.aeldit.cyansh.CyanSHServerCore.onInitializeServer(CyanSHServerCore.java:40) ~[CyanSetHome-0.1.5+1.20.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
        ... 7 more
``

**Comment by ryanliii** [comment]
Nevermind! Deleting the "cyansh" server in the config folder fixed the issue. Not sure what happened to the config, but something was preventing it from starting the server. I believe it unfortunately deleted all players existing homes though but that's not a big deal. Maybe just something worth looking into if it's a common occurrence.

**Comment by Aeldit** [comment]
Yeah in the log there appears to be a problem when parsing the json file.
Did you happen to edit the file by hand (even once) or not at all? If not, there might indeed be bug

**Comment by Aeldit** [comment]
Also do you still have the file? If so I could investigate the problem and fix it
